# testowa konfiguracja

MODE: "dev"
JS_VERSION: "0.0.0"
CSS_VERSION: "0.0.0"
app_url: "http://mydomain.pl/site"
templates_path: "templates"
cache_path: "cache"
translation_path: "translation/pl"
routes_path: "config/routes.yaml"